<div>
<img src=https://www.institutedata.com/wp-content/uploads/2019/10/iod_h_tp_primary_c.svg width="300">
</div>

# Lab 2.1.1 
# *Data Wrangling and Munging with Pandas*

## Part 1: Wrangling Data

The term "data wrangling" is analogous to capturing wild horses and getting them into a fenced area; the horses are data and the fencing is your computer. The more common data wrangling tasks include:

- reading flat files
- reading Excel files
- downloading from web pages
  - csv
  - html
  - json

In [2]:
import numpy as np
import pandas as pd

*It is good practice to display the library version numbers for future reference:*

In [3]:
print('Numpy: ', np.__version__)
print('Pandas: ', pd.__version__)

Numpy:  1.20.1
Pandas:  1.2.4


### CSV Files

Below are three attempts to load the file "bikeshare.csv" into a DataFrame named `bikes`. Why are they wrong?

In [4]:
# wrong:
bikes = pd.read_table('bikeshare.csv', header = None)
print(bikes.head())
print()

# wrong:
bikes = pd.read_table('bikeshare.csv', header = 1)
print(bikes.head())
print()

# wrong:
bikes = pd.read_table('bikeshare.csv', header = 0)
print(bikes.head())

                                                   0
0  instant,dteday,season,yr,mnth,hr,holiday,weekd...
1  1,2011-01-01,1,0,1,0,0,6,0,1,0.24,0.2879,0.81,...
2  2,2011-01-01,1,0,1,1,0,6,0,1,0.22,0.2727,0.8,0...
3  3,2011-01-01,1,0,1,2,0,6,0,1,0.22,0.2727,0.8,0...
4  4,2011-01-01,1,0,1,3,0,6,0,1,0.24,0.2879,0.75,...

  1,2011-01-01,1,0,1,0,0,6,0,1,0.24,0.2879,0.81,0,3,13,16
0  2,2011-01-01,1,0,1,1,0,6,0,1,0.22,0.2727,0.8,0...     
1  3,2011-01-01,1,0,1,2,0,6,0,1,0.22,0.2727,0.8,0...     
2  4,2011-01-01,1,0,1,3,0,6,0,1,0.24,0.2879,0.75,...     
3  5,2011-01-01,1,0,1,4,0,6,0,1,0.24,0.2879,0.75,...     
4  6,2011-01-01,1,0,1,5,0,6,0,2,0.24,0.2576,0.75,...     

  instant,dteday,season,yr,mnth,hr,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
0  1,2011-01-01,1,0,1,0,0,6,0,1,0.24,0.2879,0.81,...                                                                   
1  2,2011-01-01,1,0,1,1,0,6,0,1,0.22,0.2727,0.8,0...                                        

?ANSWER: Code 1 makes headings a data row. Code 2 makes the data in the first row as the column headings. Code 3 makes the data names as headers.

Load the file "bikeshare.csv" into a DataFrame named `bikes`, and confirm that it was loaded properly:

In [6]:
#ANSWER:
bikes = pd.read_table('bikeshare.csv', header = 0, delimiter = ',')
bikes.head()

instant      dteday  season  yr  mnth  hr  holiday  weekday  workingday  \
0        1  2011-01-01       1   0     1   0        0        6           0   
1        2  2011-01-01       1   0     1   1        0        6           0   
2        3  2011-01-01       1   0     1   2        0        6           0   
3        4  2011-01-01       1   0     1   3        0        6           0   
4        5  2011-01-01       1   0     1   4        0        6           0   

   weathersit  temp   atemp   hum  windspeed  casual  registered  cnt  
0           1  0.24  0.2879  0.81        0.0       3          13   16  
1           1  0.22  0.2727  0.80        0.0       8          32   40  
2           1  0.22  0.2727  0.80        0.0       5          27   32  
3           1  0.24  0.2879  0.75        0.0       3          10   13  
4           1  0.24  0.2879  0.75        0.0       0           1    1

Note that we could have used `read.csv()` above. When is `read_table()` necessary?

Flat files can be full of surprises. Here are some issues to watch out for:

- separator character is something other than the comma
  - ";", "|", and tab are popular
- newline character is something other than what the O/S expects 
  - Tip: Don't hard-code the character codes for carriage returns, linefeeds, etc. Use Python's built-in representation instead (e.g. Python translates "\n" to the newline character and "\t" to the tab character on any O/S).
- truncated lines
  - if there are empty fields at the end of a line it is possible that their separators will be missing, resulting in a "jagged" file
- embedded commas or quotes
  - a free-text field containing embedded commas may split into separate fields on input
  - a free-text field containing embedded quotes may not parse correctly
- unescaped characters
  - the "\" character indicates a control code to Python, which will break the I/O
    - e.g. the substring "\u0123" will be interpreted as Unicode(0123) -- which may not be what the file creator intended
  - these may need to be fixed by loading whole strings and then parsing into a new data frame
  
Tip: Most issues can be delth with by correctly specifying the parameters of the function you use to load the file. Read the doco before reading the data!

### Reading Excel Files

In [8]:
from pandas import ExcelFile  # Nb. Need to install xlrd from conda (it does not automatically install with pandas)

In [8]:
df = pd.read_excel('Iris.xls', sheet_name = 'Data')
df

Species_No  Petal_width  Petal_length  Sepal_width  Sepal_length  \
0             1          0.2           1.4          3.5           5.1   
1             1          0.2           1.4          3.0           4.9   
2             1          0.2           1.3          3.2           4.7   
3             1          0.2           1.5          3.1           4.6   
4             1          0.2           1.4          3.6           5.0   
..          ...          ...           ...          ...           ...   
145           3          2.3           5.2          3.0           6.7   
146           3          1.9           5.0          2.5           6.3   
147           3          2.0           5.2          3.0           6.5   
148           3          2.3           5.4          3.4           6.2   
149           3          1.8           5.1          3.0           5.9   

    Species_name  
0         Setosa  
1         Setosa  
2         Setosa  
3         Setosa  
4         Setosa  
..           ...  
145    Verginica  
146    Verginica  
147    Verginica  
148    Verginica  
149    Verginica  

[150 rows x 6 columns]

So, this file appears to have an embedded table of aggregates on the same sheet as the raw data (a naughty but common practice amongst analysts).

It is usually better to load data correctly than to meddle with the source file or load it 'warts and all' and then try to parse it in code. The Pandas functions for reading files have parameters that provide the control we need. For ecxample, we could make multiple calls to `read_excel()`, using combinations of the `header`, `usecols`, `skiprows`, `nrows`, and `skipfooter` parameters to load one table at a time from a spreadsheet with multiple tables.

Load the above file without the unwanted columns:

In [10]:
#ANSWER
df = pd.read_excel('Iris.xls', sheet_name = 'Data', header = 0, usecols = "B:F")
df

Petal_width  Petal_length  Sepal_width  Sepal_length Species_name
0            0.2           1.4          3.5           5.1       Setosa
1            0.2           1.4          3.0           4.9       Setosa
2            0.2           1.3          3.2           4.7       Setosa
3            0.2           1.5          3.1           4.6       Setosa
4            0.2           1.4          3.6           5.0       Setosa
..           ...           ...          ...           ...          ...
145          2.3           5.2          3.0           6.7    Verginica
146          1.9           5.0          2.5           6.3    Verginica
147          2.0           5.2          3.0           6.5    Verginica
148          2.3           5.4          3.4           6.2    Verginica
149          1.8           5.1          3.0           5.9    Verginica

[150 rows x 5 columns]

### Importing Data Directly from the Web

We usually want to store a local copy of a data file that we download from the Web, but when data retention is not a priority it is convenient to download the data directly into our running Python environment.

#### Importing Text Files from the Web

The web is the 'wild west' of data formats. However, we can usually expect good behaviour from files that are automatically generated by a service, such as the earthquake report:

In [15]:
df = pd.read_csv('https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/2.5_hour.csv')
df.head()

Empty DataFrame
Columns: [time, latitude, longitude, depth, mag, magType, nst, gap, dmin, rms, net, id, updated, place, type, horizontalError, depthError, magError, magNst, status, locationSource, magSource]
Index: []

[0 rows x 22 columns]

#### Importing HTML Files from the Web

Working with unstructured HTML files relies heavily on library functions. This one, however, is well-structured:

In [17]:
url = 'https://www.fdic.gov/resources/resolutions/bank-failures/failed-bank-list/'

# Load 
df = pd.read_html(url)[0]
df

Bank NameBank           CityCity StateSt  CertCert  \
0                    Almena State Bank             Almena      KS     15426   
1           First City Bank of Florida  Fort Walton Beach      FL     16748   
2                 The First State Bank      Barboursville      WV     14361   
3                   Ericson State Bank            Ericson      NE     18265   
4     City National Bank of New Jersey             Newark      NJ     21111   
..                                 ...                ...     ...       ...   
558                 Superior Bank, FSB           Hinsdale      IL     32646   
559                Malta National Bank              Malta      OH      6629   
560    First Alliance Bank & Trust Co.         Manchester      NH     34264   
561  National State Bank of Metropolis         Metropolis      IL      3815   
562                   Bank of Honolulu           Honolulu      HI     21029   

                 Acquiring InstitutionAI Closing DateClosing  FundFund  
0                            Equity Bank    October 23, 2020     10538  
1              United Fidelity Bank, fsb    October 16, 2020     10537  
2                         MVB Bank, Inc.       April 3, 2020     10536  
3             Farmers and Merchants Bank   February 14, 2020     10535  
4                        Industrial Bank    November 1, 2019     10534  
..                                   ...                 ...       ...  
558                Superior Federal, FSB       July 27, 2001      6004  
559                    North Valley Bank         May 3, 2001      4648  
560  Southern New Hampshire Bank & Trust    February 2, 2001      4647  
561              Banterra Bank of Marion   December 14, 2000      4646  
562                   Bank of the Orient    October 13, 2000      4645  

[563 rows x 7 columns]

#### Importing XML Files from the Web

XML files are semi-structured, but you're at the mercy of the file creator. If every record has the same format it will be much easier, but practical applications often require a lot of custom code. Here is an example that includes a nice parser class: http://www.austintaylor.io/lxml/python/pandas/xml/dataframe/2016/07/08/convert-xml-to-pandas-dataframe/

In [24]:
url = 'http://www.austintaylor.io/lxml/python/pandas/xml/dataframe/2016/07/08/convert-xml-to-pandas-dataframe/'

# Load the XML file into a data frame
df = pd.read_html(url)[0]
df.head()

Unnamed: 0        ID                                             String  \
0           0  id_a_f_3              !Susie (http://www.sync2it.com/susie)   
1           1  id_a_f_6  <a href='http://www.unchaos.com/'> UnChaos </a...   
2           2  id_a_f_7  <a href='http://www.unchaos.com/'> UnChaos Bot...   

                                       Description Type       Comment  \
0  Sync2It bookmark management & clustering engine  C R          None   
1                             UnCHAOS search robot    R  Site is dead   
2                             UnCHAOS search robot    R  Site is dead   

                     Link1 Link2  
0   http://www.sync2it.com  None  
1  http://www.unchaos.com/  None  
2  http://www.unchaos.com/  None

#### Importing JSON Files from the Web
https://www.dataquest.io/blog/python-json-tutorial/

Like XML, JSON files are semi-structured and may require work to capture the schema into a dataframe. Here is a simple example: 

In [25]:
url = 'https://raw.githubusercontent.com/chrisalbon/simulated_datasets/master/data.json'

# Load the first sheet of the JSON file into a data frame
df = pd.read_json(url, orient = 'columns')
df.head()

integer            datetime  category
0        5 2015-01-01 00:00:00         0
1        5 2015-01-01 00:00:01         0
2        9 2015-01-01 00:00:02         0
3        6 2015-01-01 00:00:03         0
4        6 2015-01-01 00:00:04         0

## Part 2: Data Munging

Data munging is manipulating data to get it into a form that we can start running analyses on (which usually means getting the data into a DataFrame). Before we get to this stage, we may need to remove headers or footers, transpose columns to rows, split wide data tables into long ones, and so on. (Nb. Excel files can be particularly troublesome, because users can format their data in mixed, complex shapes.) Essentially, we need to follow Hadley Wickham's guidelines for tidy datasets (http://vita.had.co.nz/papers/tidy-data.html):

The end goal of the cleaning data process:

- each variable should be in one column
- each observation should comprise one row
- each type of observational unit should form one table
- include key columns for linking multiple tables
- the top row contains (sensible) variable names
- in general, save data as one file per table


### Dataset Morphology

Once we have our dataset in a DataFrame (or Series, if our data is only 1-dimensional), we can start examining its size and content.

How many rows and columns are in `bikes`?

In [18]:
#ANSWER


(17379, 17)

What are the column names in `bikes`?

In [51]:
#ANSWER
for col in bikes.columns:
    print(col)

instant,dteday,season,yr,mnth,hr,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt


What are the data types of these columns?

In [19]:
#ANSWER
bikes.dtypes

instant         int64
dteday         object
season          int64
yr              int64
mnth            int64
hr              int64
holiday         int64
weekday         int64
workingday      int64
weathersit      int64
temp          float64
atemp         float64
hum           float64
windspeed     float64
casual          int64
registered      int64
cnt             int64
dtype: object

What is the (row) index for this DataFrame?

In [47]:
#ANSWER
bikes.index

RangeIndex(start=0, stop=17379, step=1)

## Slicing and Dicing

It is often preferable to refer to DataFrame columns by name, but there is more than one way to do this. 
Do `bikes['season']` and `bikes[['season']]` give the same object? Demonstrate:

In [20]:
#ANSWER
print(bikes['atemp'].head())
print(type(bikes['atemp']))
print(bikes[['atemp']].head())
print(type(bikes[['atemp']]))

type(bikes['season']) == type(bikes[['season']])

0    0.2879
1    0.2727
2    0.2727
3    0.2879
4    0.2879
Name: atemp, dtype: float64
<class 'pandas.core.series.Series'>
    atemp
0  0.2879
1  0.2727
2  0.2727
3  0.2879
4  0.2879
<class 'pandas.core.frame.DataFrame'>


False

How would we use object notation to show the first 4 rows of `atemp`?

In [21]:
#ANSWER
#N.B: Call atemp as an object, don't use .head()
bikes.atemp[:4]

0    0.2879
1    0.2727
2    0.2727
3    0.2879
Name: atemp, dtype: float64

What is the correct way to access the 1st row of the DataFrame by its index?

In [27]:
#ANSWER
print(bikes[:1])
bikes.iloc[0]

   instant      dteday  season  yr  mnth  hr  holiday  weekday  workingday  \
0        1  2011-01-01       1   0     1   0        0        6           0   

   weathersit  temp   atemp   hum  windspeed  casual  registered  cnt  
0           1  0.24  0.2879  0.81        0.0       3          13   16  


instant                1
dteday        2011-01-01
season                 1
yr                     0
mnth                   1
hr                     0
holiday                0
weekday                6
workingday             0
weathersit             1
temp                0.24
atemp             0.2879
hum                 0.81
windspeed            0.0
casual                 3
registered            13
cnt                   16
Name: 0, dtype: object

What is the correct way to access the 2nd column of the DataFrame by its index?

In [28]:
#ANSWER
bikes.iloc[:,1]

0        2011-01-01
1        2011-01-01
2        2011-01-01
3        2011-01-01
4        2011-01-01
            ...    
17374    2012-12-31
17375    2012-12-31
17376    2012-12-31
17377    2012-12-31
17378    2012-12-31
Name: dteday, Length: 17379, dtype: object

## Handling Missing Values

What is the Pandas `isnull` function for? 

We can apply `isnull` to the `bikes` DataFrame to show the result for every element:

In [31]:
#ANSWER
bikes.isnull().head()

instant  dteday  season     yr   mnth     hr  holiday  weekday  workingday  \
0    False   False   False  False  False  False    False    False       False   
1    False   False   False  False  False  False    False    False       False   
2    False   False   False  False  False  False    False    False       False   
3    False   False   False  False  False  False    False    False       False   
4    False   False   False  False  False  False    False    False       False   

   weathersit   temp  atemp    hum  windspeed  casual  registered    cnt  
0       False  False  False  False      False   False       False  False  
1       False  False  False  False      False   False       False  False  
2       False  False  False  False      False   False       False  False  
3       False  False  False  False      False   False       False  False  
4       False  False  False  False      False   False       False  False

However, we usually start at a higher level. How many nulls are in `bikes` altogether?

In [22]:
#ANSWER
bikes.isna().sum().sum()

0

If this result were nonzero we would next want to find out which columns contained nulls. How can this be done in one line of code?

In [23]:
#ANSWER
bikes.isnull().sum()

instant       0
dteday        0
season        0
yr            0
mnth          0
hr            0
holiday       0
weekday       0
workingday    0
weathersit    0
temp          0
atemp         0
hum           0
windspeed     0
casual        0
registered    0
cnt           0
dtype: int64

What is the Numpy object `nan` used for? (Write a descriptive answer.)

Write (and verify) a function that performs scalar division with built-in handling of the edge case (i.e. return a value instead of just trapping the error):

In [24]:
#ANSWER
def divide(dividend, divisor):
    if divisor == 0:
        quotient = np.nan
    else:
        quotient = dividend / divisor
    return (quotient)

print(divide(1, 0))

nan


Apply the Pandas `isna` function to the following data objects:

In [25]:
#ANSWER
x = 2.3
y = np.nan
print(x, y)

2.3 nan


In [26]:
#ANSWER
print(pd.isna(x),pd.isna(y))

False True


In [27]:
#ANSWER
array = np.array([[1, np.nan, 3], [4, 5, np.nan]])
print(array)

[[ 1. nan  3.]
 [ 4.  5. nan]]


In [28]:
#ANSWER
pd.isna(array)

array([[False,  True, False],
       [False, False,  True]])

How is the pandas I/O parameter `na_values` used?

## Data Profiling

### Counts

When there are categorical variables in a dataset we will want to know how many possible values there are in each column. (Nb. If the dataset is a sample of a larger one, our sample may not capture all possible values of every categorical.)

How many (different) seasons are in `bikes`?

In [29]:
#ANSWER
bikes[['season']].value_counts()

season
3         4496
2         4409
1         4242
4         4232
dtype: int64

### Ranges

Print the range of the `instant`, `dteday`, and `windspeed` columns: 

In [30]:
#ANSWER
print('instant:', bikes['instant'].min(), 'to', bikes['instant'].max())
print('dteday:', bikes['dteday'].min(), 'to', bikes['dteday'].max())
print('windspeed:', bikes['windspeed'].min(), 'to', bikes['windspeed'].max())

instant: 1 to 17379
dteday: 2011-01-01 to 2012-12-31
windspeed: 0.0 to 0.8507


Compute and print the overall minimum and maximum of the numeric data columns:

In [31]:
#ANSWER
bikes_min = min(bikes.min(numeric_only=True))
bikes_max = max(bikes.max(numeric_only=True))
bikes_min, bikes_max

(0.0, 17379.0)

### Quantiles

Pandas makes computing quantiles easy. This is how to get the median of a Series:

In [32]:
#ANSWER
bikes['atemp'].quantile(0.5)

0.4848

Of course, the `quantiles` method can take a tuple as its argument. Compute the 10th, 25th, 50th, 75th, and 90th percentiles in one line of code: 

In [33]:
#ANSWER
bikes['atemp'].quantile([0.1,0.25,0.5,0.75,0.9])

0.10    0.2424
0.25    0.3333
0.50    0.4848
0.75    0.6212
0.90    0.6970
Name: atemp, dtype: float64

### Cuts

Sometimes we want to split the sample not by the quantiles of the distribution but by the range of the data. Let's take a closer look at `atemp`:

In [34]:
#ANSWER
type(bikes['atemp'])

pandas.core.series.Series

In [35]:
#ANSWER
bikes.sample(5)

instant      dteday  season  yr  mnth  hr  holiday  weekday  workingday  \
2116     2117  2011-04-03       2   0     4   1        0        0           0   
9480     9481  2012-02-04       1   1     2  22        0        6           0   
969       970  2011-02-13       1   0     2   0        0        0           0   
7437     7438  2011-11-11       4   0    11  12        1        5           0   
9992     9993  2012-02-26       1   1     2   9        0        0           0   

      weathersit  temp   atemp   hum  windspeed  casual  registered  cnt  
2116           1  0.30  0.3182  0.61     0.1045       8          26   34  
9480           2  0.24  0.2576  0.87     0.0896       4          91   95  
969            1  0.20  0.2273  0.64     0.1045       5          34   39  
7437           1  0.34  0.2879  0.42     0.4627      41         198  239  
9992           1  0.22  0.2121  0.47     0.2239      11          76   87

Suppose we decide to sort these values into 4 bins of equal width, but we want to apply the resulting groups to the entire DataFrame. Basically, we need to add a row label that indcates which bin each sample belongs in. Let's call this label "atemp_level", and use the `cut` method to populate it:

In [36]:
#ANSWER
atemp_level = pd.cut(bikes['atemp'], bins = 4)         

What is `atemp_level`?

In [37]:
#ANSWER
print(type(atemp_level))
print(atemp_level)

<class 'pandas.core.series.Series'>
0        (0.25, 0.5]
1        (0.25, 0.5]
2        (0.25, 0.5]
3        (0.25, 0.5]
4        (0.25, 0.5]
            ...     
17374    (0.25, 0.5]
17375    (0.25, 0.5]
17376    (0.25, 0.5]
17377    (0.25, 0.5]
17378    (0.25, 0.5]
Name: atemp, Length: 17379, dtype: category
Categories (4, interval[float64]): [(-0.001, 0.25] < (0.25, 0.5] < (0.5, 0.75] < (0.75, 1.0]]


Here is a random sample of `atemp_level`:

In [38]:
#ANSWER
atemp_level.sample(5)          

4239        (0.5, 0.75]
4738        (0.75, 1.0]
16240       (0.25, 0.5]
4802        (0.75, 1.0]
409      (-0.001, 0.25]
Name: atemp, dtype: category
Categories (4, interval[float64]): [(-0.001, 0.25] < (0.25, 0.5] < (0.5, 0.75] < (0.75, 1.0]]

So, by default, `cut` produces labels that indicate the bin boundaries for each element in the series it was applied to. Usually, we will specify labels that are appropriate to the discretisation we are applying:

In [39]:
#ANSWER
atemp_level = pd.cut(bikes['atemp'], bins = 4, labels = ["cool", "mild", "warm", "hot"])
atemp_level.sample(5)          

14783    mild
9438     mild
9631     cool
10437    mild
16855    mild
Name: atemp, dtype: category
Categories (4, object): ['cool' < 'mild' < 'warm' < 'hot']

Incorporate the new `atemp_level` column into the `bikes` DataFrame and use it to count the number of "mild" `atemp` entries in `season` 2:

In [40]:
#ANSWER
bikes['atemp_level'] = atemp_level

In [41]:
#ANSWER
bikes[(bikes.atemp_level == 'mild') & (bikes.season == 2)].count()

instant        1829
dteday         1829
season         1829
yr             1829
mnth           1829
hr             1829
holiday        1829
weekday        1829
workingday     1829
weathersit     1829
temp           1829
atemp          1829
hum            1829
windspeed      1829
casual         1829
registered     1829
cnt            1829
atemp_level    1829
dtype: int64

*Nb. The `atemp_level` variable we created is what the R language calls a "factor". Pandas has introduced a new data type called "category" that is similar to R's factors.*

# Synthetic Data

Sometimes we may want to generate test data, or we may need to initalise a series, matrix, or data frame for input to an algorithm. Numpy has several methods we can use for this.

Execute the following, then check the shape and content of each variable:

In [43]:
#ANSWER

a = np.zeros((3))
b = np.ones((1,3))
c = np.random.randint(1,10,(2,3,4))   # randint(low, high, size)
d = np.arange(4)
e = np.array( [[1,2,3,4], [5,6,7,8]] )

def check(a):
    print(a)
    print(type(a))
    print(a.shape)
    print('\n')
    
check(a)
check(b)
check(c)
check(d)
check(e)

[0. 0. 0.]
<class 'numpy.ndarray'>
(3,)


[[1. 1. 1.]]
<class 'numpy.ndarray'>
(1, 3)


[[[9 2 5 7]
  [6 4 4 5]
  [6 9 4 8]]

 [[1 9 9 3]
  [1 6 3 4]
  [2 8 1 2]]]
<class 'numpy.ndarray'>
(2, 3, 4)


[0 1 2 3]
<class 'numpy.ndarray'>
(4,)


[[1 2 3 4]
 [5 6 7 8]]
<class 'numpy.ndarray'>
(2, 4)




## Load Data

Load rock.csv and clean the dataset.

In [32]:
#ANSWER
rock = pd.read_csv('rock.csv')
rock.head()

Song Clean ARTIST CLEAN Release Year  \
0        Caught Up in You  .38 Special         1982   
1            Fantasy Girl  .38 Special          NaN   
2         Hold On Loosely  .38 Special         1981   
3  Rockin' Into the Night  .38 Special         1980   
4       Art For Arts Sake         10cc         1975   

                                COMBINED  First?  Year?  PlayCount  F*G  
0        Caught Up in You by .38 Special       1      1         82   82  
1            Fantasy Girl by .38 Special       1      0          3    0  
2         Hold On Loosely by .38 Special       1      1         85   85  
3  Rockin' Into the Night by .38 Special       1      1         18   18  
4              Art For Arts Sake by 10cc       1      1          1    1

## Check Column Names

Check column names and clean.

In [46]:
#ANSWER
rock.columns

Index(['Song Clean', 'ARTIST CLEAN', 'Release Year', 'COMBINED', 'First?',
       'Year?', 'PlayCount', 'F*G'],
      dtype='object')

In [47]:
#ANSWER
def clean_column_name(column_names):
    clean_column_names = []
    for c in column_names:
        c = c.lower().replace(' ', '_')
        c = c.lower().replace('*', '')
        c = c.lower().replace('?', '')
        clean_column_names.append(c)
        
    return clean_column_names

In [48]:
#ANSWER
rock.columns = clean_column_name(rock.columns)

## Replace Null Values With 0

Check 'release' column whether this column have any null value or not. Replace null value with 0.

In [49]:
#ANSWER
rock['release_year'].isnull().sum()

577

In [50]:
#ANSWER
rock['release_year'].fillna(0, inplace=True)

## Check Datatypes of Dataset

Check datatypes of the dataset. Is there any column which should be int instead of object? Fix the column. 

In [51]:
#ANSWER
rock.dtypes

song_clean      object
artist_clean    object
release_year    object
combined        object
first            int64
year             int64
playcount        int64
fg               int64
dtype: object

In [52]:
#ANSWER
rock.drop(columns=['first','fg','year'], inplace=True)

## Check Min, Max of Each Column


Is there any illogical value in any column? How can we fix that?

In [53]:
# SONGFACTS.COM is listed as a release year
rock['release_year'].value_counts()
rock['release_year'].replace('SONGFACTS.COM', 0, inplace=True)

In [54]:
rock['release_year'] = rock['release_year'].astype(int)

In [55]:
def check_min_max(df):
    # Check min, max of each column
    print(df.describe().T[['min', 'max']])
check_min_max(rock)

              min     max
release_year  0.0  2014.0
playcount     0.0   142.0


In [56]:
# 0 and 1071 are listed as release years in dataframe
rock = rock[rock['release_year'] != 0]
rock = rock[rock['release_year'] != 1071]

In [57]:
check_min_max(rock)

                 min     max
release_year  1955.0  2014.0
playcount        0.0   142.0


# Write Some Functions

In [58]:
def find_albumography(df,artist):
    """Returns songs of an artist and their release year."""
    count = df[['Song Clean','Release Year']][df['ARTIST CLEAN'] == artist]
    return count
#print(find_albumography(rock, 'ZZ Top'))

In [59]:
def song_of_year(df,year):
    """Return songs of a certain year"""
    if type(year) != int:
        return ValueError('Please put parameter year as int, not str')
    rel_year = df['COMBINED'][df['Release Year'] == year]
    return rel_year
#print(song_of_year(rock, '1983'))
#print(song_of_year(rock, 1983))

In [60]:
def more_popular(df,count):
    """Return songs that are more popular than the playcount listed"""
    more_popular = df[['COMBINED','Release Year','PlayCount']][df['PlayCount'] >= count]
    more_popular.sort_values('PlayCount',inplace=True)
    return more_popular
#print(more_popular(rock, 20))

## Write a function that will take a row of a DataFrame and print out the song, artist, and whether or not the release date is < 1970

In [61]:
def check_song(row):
    print('Song: ', row['song_clean'])
    print('Artist: ', row['artist_clean'])
    print('Released before 1970: ', row['release_year'] < 1970)
    print('\n')

In [62]:
# Check any row using index
check_song(rock.iloc[0])

Song:  Caught Up in You
Artist:  .38 Special
Released before 1970:  False




In [63]:
# Check first five rows
rock.head(5).apply(check_song, axis=1)

Song:  Caught Up in You
Artist:  .38 Special
Released before 1970:  False


Song:  Hold On Loosely
Artist:  .38 Special
Released before 1970:  False


Song:  Rockin' Into the Night
Artist:  .38 Special
Released before 1970:  False


Song:  Art For Arts Sake
Artist:  10cc
Released before 1970:  False


Song:  Kryptonite
Artist:  3 Doors Down
Released before 1970:  False




0    None
2    None
3    None
4    None
5    None
dtype: object

## Write a function that converts cells in a DataFrame to float and otherwise replaces them with np.nan

In [64]:
rock_f = rock.copy()

In [65]:
def convert_to_float(column):
    column = pd.to_numeric(column, errors='coerce')
    return column

In [66]:
# Alternate solution
def floater(df):
    for i in df:
        if df[i].dtypes == 'int64':
            df[i] = df[i].astype(float)
        else:
            df[i] = np.NaN
    return df

## Apply these functions to your dataset

In [67]:
rock_f.apply(convert_to_float)

song_clean  artist_clean  release_year  combined  playcount
0            NaN           NaN          1982       NaN         82
2            NaN           NaN          1981       NaN         85
3            NaN           NaN          1980       NaN         18
4            NaN           NaN          1975       NaN          1
5            NaN           NaN          2000       NaN         13
...          ...           ...           ...       ...        ...
2224         NaN           NaN          1983       NaN        120
2226         NaN           NaN          1981       NaN         32
2227         NaN           NaN          1975       NaN        109
2228         NaN           NaN          1983       NaN          1
2229         NaN           NaN          1973       NaN          2

[1651 rows x 5 columns]

## Describe the new float-only DataFrame.

In [68]:
rock_f.describe()

release_year    playcount
count   1651.000000  1651.000000
mean    1978.569352    20.320412
std        9.309780    27.509222
min     1955.000000     0.000000
25%     1971.000000     2.000000
50%     1977.000000     7.000000
75%     1984.000000    28.000000
max     2014.000000   142.000000



---



---



> > > > > > > > > © 2021 Institute of Data


---



---



